apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: xinyuz0416/mern-ts-backend:latest
          envFrom:
            - secretRef:
                name: app-secrets
          ports:
            - containerPort: 5001
